import { colors } from './colors';

export const lightTheme = {
  name: 'light',
  background: colors.beige,
  card: colors.white,
  post: colors.white,
  border: colors.blue,
  mapBorder: colors.grey,
  commentInput: colors.greyAlt,
  postPetButton: 'transparent',
  postPetButtonBorder: colors.blue,
  postPetButtonText: colors.blue,
  stateButton: 'transparent',
  stateButtonBorder: colors.blue,
  stateButtonText: colors.blue,
  selectedStateButton: colors.blue,
  chip: colors.dark,
  completedStep: colors.green,
  primaryText: colors.dark,
  secondaryText: colors.darkGrey,
  inputText: colors.darkGreyAlt,
  lineDivision: colors.darkGreyAlt,
  navBackground: colors.beige,
  iconBackground: colors.beige,
  paginationText: colors.darkerDark,
  overlay: 'rgba(0, 0, 0, 0.6)',
};

export const darkTheme = {
  name: 'dark',
  background: colors.dark,
  card: colors.darkGrey,
  post: colors.dark,
  border: colors.white,
  mapBorder: colors.white,
  commentInput: colors.white,
  postPetButton: colors.green,
  postPetButtonBorder: 'transparent',
  postPetButtonText: colors.dark,
  stateButton: colors.blue,
  stateButtonText: colors.white,
  selectedStateButton: colors.green,
  chip: colors.darkerDark,
  completedStep: colors.blue,
  primaryText: colors.white,
  secondaryText: colors.white,
  inputText: colors.greyAlt,
  lineDivision: colors.white,
  navBackground: colors.dark,
  iconBackground: colors.white,
  paginationText: colors.white,
  overlay: 'rgba(255, 255, 255, 0.2)',
};