/* Obs.: o atributo 'userProfilePicture' deve ser removido quando forem utilizados os dados do backend */

export const mockedPosts = [
  {
    id: 1,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture1.png'),
    userUsername: 'Joana Dark',
    timestamp: '10/11/2025 - 08:00',
    imageUrl: require('@assets/images/PetImage1.png'),
    name: 'Beto',
    tag: 'Perdido',
    date: '00 de dezembro de 2000',
    sex: 'Macho',
    breed: 'SRD',
    temper: 'Bravo',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: [
      {
        userUsername: 'Cláudio',
        timestamp: '24/11/2025 - 16:00',
        comment: 'cachorro kkkkkkkkk'
      },
      {
        userUsername: 'Nome do Usuário',
        timestamp: '24/11/2025 - 16:00',
        comment: 'Lorem ipsum dolor sit amet conse ctetur. Suscipit tristique ullamcorper faucibus tristarcu integer descrição completa.',
      },
      {
        userUsername: 'Nome do Usuário',
        timestamp: '24/11/2025 - 16:00',
        comment: 'é um cachorro'
      }
    ]
  },
  {
    id: 2,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: [
      {
        userUsername: 'Nome do Usuário',
        timestamp: '24/11/2025 - 16:00',
        comment: 'Lorem ipsum dolor sit amet conse ctetur. Suscipit tristique ullamcorper faucibus tristarcu integer descrição completa.',
      },
      {
        userUsername: 'Nome do Usuário',
        timestamp: '24/11/2025 - 16:00',
        comment: 'fala bro yoooooooooo'
      }
    ]
  },
  {
    id: 3,
    type: 'Pet',
    userProfilePicture: require('@assets/images/gpets-profile-picture.png'),
    userUsername: 'GPets',
    timestamp: '26/11/2025 - 14:50',
    imageUrl: require('@assets/images/PetImage3.png'),
    name: 'Sem nome',
    tag: 'Resgatado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'SRD',
    temper: 'Carinhosa',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: [
      {
        userUsername: 'Nome do Usuário',
        timestamp: '24/11/2025 - 16:00',
        comment: 'Lorem ipsum dolor sit amet conse ctetur. Suscipit tristique ullamcorper faucibus tristarcu integer descrição completa.',
      }
    ]
  },
  {
    id: 4,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture4.png'),
    userUsername: 'Rafaela Ferreira',
    timestamp: '26/11/2025 - 14:50',
    imageUrl: require('@assets/images/PetImage4.png'),
    name: 'Duna',
    tag: 'Encontrado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Raça',
    temper: 'Calma',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: [
      {
        userUsername: 'Nome do Usuário',
        timestamp: '24/11/2025 - 16:00',
        comment: 'Lorem ipsum dolor sit amet conse ctetur. Suscipit tristique ullamcorper faucibus tristarcu integer descrição completa.',
      }
    ]
  },
  {
    id: 5,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture1.png'),
    userUsername: 'Joana Dark',
    timestamp: '10/11/2025 - 08:00',
    imageUrl: require('@assets/images/PetImage1.png'),
    name: 'Beto',
    tag: 'Perdido',
    date: '00 de dezembro de 2000',
    sex: 'Macho',
    breed: 'SRD',
    temper: 'Bravo',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 6,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 7,
    type: 'Pet',
    userProfilePicture: require('@assets/images/gpets-profile-picture.png'),
    userUsername: 'GPets',
    timestamp: '26/11/2025 - 14:50',
    imageUrl: require('@assets/images/PetImage3.png'),
    name: 'Sem nome',
    tag: 'Resgatado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'SRD',
    temper: 'Carinhosa',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 8,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture4.png'),
    userUsername: 'Rafaela Ferreira',
    timestamp: '26/11/2025 - 14:50',
    imageUrl: require('@assets/images/PetImage4.png'),
    name: 'Duna',
    tag: 'Encontrado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Raça',
    temper: 'Calma',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  }
]