export const mockedBookmarks = [
  {
    id: 1,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 2,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 3,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 4,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 5,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 6,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 7,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 8,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 9,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 10,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 11,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 12,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 13,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 14,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 15,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 16,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 17,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 18,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 19,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 20,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 21,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 22,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 23,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
  {
    id: 24,
    type: 'Pet',
    userProfilePicture: require('@assets/images/ProfilePicture2.png'),
    userUsername: 'Vitória Vasconcelos',
    timestamp: '24/11/2025 - 16:00',
    imageUrl: require('@assets/images/PetImage2.png'),
    isOwner: false,
    name: 'Sem nome',
    tag: 'Desabrigado',
    date: '00 de dezembro de 2000',
    sex: 'Fêmea',
    breed: 'Caramelo',
    temper: 'Amigável',
    owner: 'nome',
    phoneContact: '(+DD) 99999-9999',
    description: 'Lorem ipsum dolor sit amet consectetur. Suscipit tristique ullamcorper faucibus tristique aliquet malesuada. Tristique lorem sit sed et arcu integer.',
    adress: '',
    coordinateLat: '',
    coordinateLng: '',
    comments: []
  },
]