export const mockedNotifications = [
  {
    id: 1,
    title: 'Animal Encontrado',
    description: 'Seu animal foi encontrado pela Joana Dark na rua Av. Plácido Castelo, N 1599, Cep 63800000',
    timestamp: '09:10',
    viewed: false,
  },
  {
    id: 2,
    title: 'Novo Comentário',
    description: 'Carlos Silva comentou na sua publicação sobre o cachorro perdido.',
    timestamp: '09:35',
    viewed: false,
  },
  {
    id: 3,
    title: 'Atualização de Status',
    description: 'O status do seu post foi alterado para “Resgatado”.',
    timestamp: '10:02',
    viewed: true,
  },
  {
    id: 4,
    title: 'Animal Avistado',
    description: 'Um possível avistamento foi registrado próximo à Praça Central.',
    timestamp: '10:18',
    viewed: false,
  },
  {
    id: 5,
    title: 'Mensagem Recebida',
    description: 'Você recebeu uma nova mensagem de Mariana Lopes.',
    timestamp: '11:05',
    viewed: false,
  },
  {
    id: 6,
    title: 'Evento Próximo',
    description: 'O evento “Feira de Adoção” acontece hoje às 14h no Parque Municipal.',
    timestamp: '11:42',
    viewed: false,
  },
  {
    id: 7,
    title: 'Postagem Curtida',
    description: 'Rafael Mendes curtiu sua publicação.',
    timestamp: '12:10',
    viewed: true,
  },
  {
    id: 8,
    title: 'Novo Seguidor',
    description: 'Ana Paula começou a seguir seu perfil.',
    timestamp: '13:27',
    viewed: true,
  },
  {
    id: 9,
    title: 'Animal Encontrado',
    description: 'Seu animal foi encontrado nas proximidades da Rua das Flores.',
    timestamp: '14:03',
    viewed: false,
  },
  {
    id: 10,
    title: 'Lembrete',
    description: 'Não se esqueça de atualizar as informações da sua publicação.',
    timestamp: '15:20',
    viewed: false,
  },
  {
    id: 11,
    title: 'Animal Encontrado',
    description: 'Seu animal foi encontrado pela Joana Dark na rua Av. Plácido Castelo, N 1599, Cep',
    timestamp: '09:10',
    viewed: false,
  },
  {
    id: 12,
    title: 'Novo Comentário',
    description: 'Carlos Silva comentou na sua publicação sobre o cachorro perdido.',
    timestamp: '09:35',
    viewed: true,
  },
  {
    id: 13,
    title: 'Atualização de Status',
    description: 'O status do seu post foi alterado para “Resgatado”.',
    timestamp: '10:02',
    viewed: false,
  },
  {
    id: 14,
    title: 'Animal Avistado',
    description: 'Um possível avistamento foi registrado próximo à Praça Central.',
    timestamp: '10:18',
    viewed: true,
  },
  {
    id: 15,
    title: 'Mensagem Recebida',
    description: 'Você recebeu uma nova mensagem de Mariana Lopes.',
    timestamp: '11:05',
    viewed: false,
  }
];