export const mockedMessages = [
  {
    messages: [
      { content: 'Bom dia!!', timestamp: '09:10' },
    ],
    user: {
      id: 101,
      role: 'USER',
      name: 'Joana Dark',
      email: 'joanadark@gmail.com',
      password: 'joanadarksenha',
      bio: 'Olá, bem-vindos ao meu perfil :)',
      phone: '(88) 99613-3521',
      imageUrl: require('@assets/images/ProfilePicture1.png'),
    },
  },
  {
    messages: [
      { content: 'Bom dia!', timestamp: '10:05' },
      { content: 'Você conseguiu mais informações?', timestamp: '10:08' },
      { content: 'Qualquer coisa me avisa.', timestamp: '10:12' },
    ],
    user: {
      id: 102,
      role: 'USER',
      name: 'Vitória Vasconcelos',
      email: 'vitoria.v@gmail.com',
      password: 'vitoriasegura123',
      bio: 'Amante de animais e voluntária sempre que posso 🐾',
      phone: '(11) 98765-4321',
      imageUrl: require('@assets/images/ProfilePicture2.png'),
    },
  },
  {
    messages: [
      { content: 'Olá! Recebemos uma denúncia semelhante.', timestamp: '14:30' },
      { content: 'Estamos verificando.', timestamp: '14:35' },
      { content: 'Obrigado por avisar.', timestamp: '14:39' },
    ],
    user: {
      id: 103,
      role: 'USER',
      name: 'GPets',
      email: 'contato@gpets.com',
      password: 'gpetsadmin',
      bio: 'Plataforma dedicada ao cuidado e proteção animal.',
      phone: '(11) 90000-0000',
      imageUrl: require('@assets/images/gpets-profile-picture.png'),
    },
  },
  {
    messages: [
      { content: 'Boa tarde!', timestamp: '15:02' },
    ],
    user: {
      id: 104,
      role: 'USER',
      name: 'Rafael Ferreira',
      email: 'rafael.ferreira@gmail.com',
      password: 'rafael123',
      bio: 'Sempre disposto a ajudar quando posso.',
      phone: '(21) 98888-7766',
      imageUrl: require('@assets/images/ProfilePicture4.png'),
    },
  },
  {
    messages: [
      { content: 'Você sabe se o animal já foi resgatado?', timestamp: '16:40' },
      { content: 'Estou tentando ajudar.', timestamp: '16:43' },
      { content: 'Me avisa, qualquer coisa :)', timestamp: '16:45' },
    ],
    user: {
      id: 105,
      role: 'USER',
      name: 'Lucas Almeida',
      email: 'lucas.almeida@gmail.com',
      password: 'lucasalmeida',
      bio: 'Gosto de ajudar causas sociais.',
      phone: '(31) 97777-6655',
      imageUrl: require('@assets/images/ProfilePicture5.png'),
    },
  },
  {
    messages: [
      { content: 'Oi!', timestamp: '18:10' },
      { content: 'Vi o cachorro ontem à noite.', timestamp: '18:14' },
      { content: 'Ele parecia assustado.', timestamp: '18:17' },
      { content: 'Estava perto do mercado.', timestamp: '18:20' },
    ],
    user: {
      id: 106,
      role: 'USER',
      name: 'Marina Costa',
      email: 'marina.costa@gmail.com',
      password: 'marinacosta',
      bio: 'Apaixonada por pets e pela natureza.',
      phone: '(19) 96666-5544',
      imageUrl: require('@assets/images/ProfilePicture6.png'),
    },
  },
  {
    messages: [
      { content: 'Boa noite.', timestamp: '19:05' },
      { content: 'Consegue me passar mais detalhes?', timestamp: '19:10' },
    ],
    user: {
      id: 107,
      role: 'USER',
      name: 'Rafael Nogueira',
      email: 'rafael.nogueira@gmail.com',
      password: 'rafaelnogueira',
      bio: 'Morador da região, atento ao que acontece.',
      phone: '(41) 95555-4433',
      imageUrl: require('@assets/images/ProfilePicture7.png'),
    },
  },
  {
    messages: [
      { content: 'Oi!', timestamp: '19:55' },
      { content: 'Compartilhei o post com meus amigos.', timestamp: '20:00' },
      { content: 'Vamos achar esse pet!', timestamp: '20:05' },
    ],
    user: {
      id: 108,
      role: 'USER',
      name: 'Camila Ribeiro',
      email: 'camila.ribeiro@gmail.com',
      password: 'camilasenha',
      bio: 'Ajudar é sempre o melhor caminho 💛',
      phone: '(85) 94444-3322',
      imageUrl: require('@assets/images/ProfilePicture8.png'),
    },
  },
  {
    messages: [
      { content: 'Boa noite!', timestamp: '21:20' },
      { content: 'Tenho notícias importantes.', timestamp: '21:25' },
      { content: 'Acho que encontrei o cachorro.', timestamp: '21:30' },
    ],
    user: {
      id: 109,
      role: 'USER',
      name: 'Pedro Martins',
      email: 'pedro.martins@gmail.com',
      password: 'pedromartins',
      bio: 'Sempre atento ao bairro.',
      phone: '(62) 93333-2211',
      imageUrl: require('@assets/images/ProfilePicture9.png'),
    },
  },
  {
    messages: [
      { content: 'Olá!', timestamp: '08:15' },
    ],
    user: {
      id: 110,
      role: 'USER',
      name: 'Ana Paula Souza',
      email: 'ana.souza@gmail.com',
      password: 'anapaula',
      bio: 'Gosto de colaborar quando posso.',
      phone: '(71) 92222-1100',
      imageUrl: require('@assets/images/ProfilePicture1.png'),
    },
  },
  {
  messages: [
    { content: 'Oi!', timestamp: '09:30' },
    { content: 'Tudo bem?', timestamp: '09:35' },
    { content: 'Queria ajudar no resgate.', timestamp: '09:40' },
  ],
  user: {
    id: 111,
    role: 'USER',
    name: 'Bruno Henrique',
    email: 'bruno.henrique@gmail.com',
    password: 'brunohenrique',
    bio: 'Sempre disposto a ajudar em boas causas.',
    phone: '(11) 91111-2233',
    imageUrl: require('@assets/images/ProfilePicture4.png'),
  },
  },
  {
    messages: [
      { content: 'Bom dia!', timestamp: '10:50' },
      { content: 'Vi sua publicação.', timestamp: '10:55' },
    ],
    user: {
      id: 112,
      role: 'USER',
      name: 'Carolina Mendes',
      email: 'carolina.mendes@gmail.com',
      password: 'carolinamendes',
      bio: 'Acredito no poder da colaboração.',
      phone: '(21) 92222-3344',
      imageUrl: require('@assets/images/ProfilePicture2.png'),
    },
  },
  {
    messages: [
      { content: 'Boa tarde.', timestamp: '13:10' },
      { content: 'Tenho uma informação nova.', timestamp: '13:14' },
      { content: 'Pode me ligar?', timestamp: '13:18' },
    ],
    user: {
      id: 113,
      role: 'USER',
      name: 'Diego Azevedo',
      email: 'diego.azevedo@gmail.com',
      password: 'diegoazevedo',
      bio: 'Sempre atento ao que acontece na região.',
      phone: '(31) 93333-4455',
      imageUrl: require('@assets/images/ProfilePicture9.png'),
    },
  },
  {
    messages: [
      { content: 'Oi!', timestamp: '13:58' },
      { content: 'Espero que consigam encontrar logo.', timestamp: '14:02' },
    ],
    user: {
      id: 114,
      role: 'USER',
      name: 'Eduarda Lima',
      email: 'eduarda.lima@gmail.com',
      password: 'eduardalima',
      bio: 'Torcendo sempre por finais felizes 🐶',
      phone: '(85) 94444-5566',
      imageUrl: require('@assets/images/ProfilePicture8.png'),
    },
  },
  {
    messages: [
      { content: 'Boa noite!', timestamp: '18:40' },
      { content: 'Fiquei sabendo do caso.', timestamp: '18:44' },
      { content: 'Conte comigo.', timestamp: '18:47' },
    ],
    user: {
      id: 115,
      role: 'USER',
      name: 'Felipe Rocha',
      email: 'felipe.rocha@gmail.com',
      password: 'feliperocha',
      bio: 'Gosto de ajudar sempre que posso.',
      phone: '(41) 95555-6677',
      imageUrl: require('@assets/images/ProfilePicture5.png'),
    },
  },
  {
    messages: [
      { content: 'Oi!', timestamp: '19:50' },
      { content: 'Você precisa de ajuda com algo?', timestamp: '19:55' },
    ],
    user: {
      id: 116,
      role: 'USER',
      name: 'Gabriela Torres',
      email: 'gabriela.torres@gmail.com',
      password: 'gabrielatorres',
      bio: 'Empatia e cuidado fazem a diferença.',
      phone: '(19) 96666-7788',
      imageUrl: require('@assets/images/ProfilePicture6.png'),
    },
  },
  {
    messages: [
      { content: 'Boa noite.', timestamp: '20:30' },
      { content: 'Vi movimentação estranha perto do local.', timestamp: '20:35' },
      { content: 'Talvez valha conferir.', timestamp: '20:40' },
    ],
    user: {
      id: 117,
      role: 'USER',
      name: 'Henrique Pires',
      email: 'henrique.pires@gmail.com',
      password: 'henriquepires',
      bio: 'Observador e sempre atento ao bairro.',
      phone: '(27) 97777-8899',
      imageUrl: require('@assets/images/ProfilePicture7.png'),
    },
  },
  {
    messages: [
      { content: 'Oi!', timestamp: '21:00' },
      { content: 'Compartilhei no grupo do bairro.', timestamp: '21:05' },
    ],
    user: {
      id: 118,
      role: 'USER',
      name: 'Isabela Fontes',
      email: 'isabela.fontes@gmail.com',
      password: 'isabelafontes',
      bio: 'Ajudar é sempre importante.',
      phone: '(71) 98888-9900',
      imageUrl: require('@assets/images/ProfilePicture1.png'),
    },
  },
  {
    messages: [
      { content: 'Boa noite!', timestamp: '22:05' },
      { content: 'Alguma novidade?', timestamp: '22:10' },
    ],
    user: {
      id: 119,
      role: 'USER',
      name: 'João Victor',
      email: 'joao.victor@gmail.com',
      password: 'joaovictor',
      bio: 'Sempre acompanhando o caso.',
      phone: '(62) 99999-0011',
      imageUrl: require('@assets/images/ProfilePicture9.png'),
    },
  },
  {
    messages: [
      { content: 'Oi!', timestamp: '07:15' },
      { content: 'Vi o cachorro hoje cedo.', timestamp: '07:18' },
      { content: 'Ele estava com uma coleira azul.', timestamp: '07:21' },
      { content: 'Parecia bem cuidado.', timestamp: '07:25' },
    ],
    user: {
      id: 120,
      role: 'USER',
      name: 'Larissa Monteiro',
      email: 'larissa.monteiro@gmail.com',
      password: 'larissamonteiro',
      bio: 'Amor e cuidado pelos animais.',
      phone: '(48) 90000-1122',
      imageUrl: require('@assets/images/ProfilePicture2.png'),
    },
  },
];